rpc:
  enable: true
  port: 127.0.0.1:8080
  token: ""
  tls:
    enable: false
    cert_file: ""
    key_file: ""
debug: true
interval: 15
out_put_path: /Users/chigusa/Movies
live_rooms:
- https://www.panda.tv/10300
- https://live.bilibili.com/1010
